Added Spanish Translation
MightyPirates/TIS-3D pull request #118
Opened 2020-09-28 16:42 UTC by GasInfinity

I added spanish language file

2020-09-29 08:18 UTC, Sturmlilie commented
Thank you very much, I'll have someone proof read it :)

2020-09-30 21:02 UTC, Sturmlilie commented
Some feedback from discord:
```
Mr Louwind: code_book should be "Libro de Código" o "Manual de Código"
Mr Louwind: Also, it's Recibir not Recivir
Mr Louwind: And Módulo not Modulo
```

2020-10-01 05:11 UTC, GasInfinity commented
Oh, sorry, I will change it

2020-10-25 13:44 UTC, FlashyReese requested changes
I decided to look over this as requested from the Fabric Translator's Guild
Here is the discord invite https://discord.gg/cDJVatJ
You can find on there

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.invalid_instruction": "Opcode Invalido",
```suggestion
    "tis3d.compiler.invalid_instruction": "Opcode inválido",
```
or
```suggestion
    "tis3d.compiler.invalid_instruction": "Código de operación inválido",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.label_duplicate": "La etiqueta ya esta definida",
```suggestion
    "tis3d.compiler.label_duplicate": "La etiqueta ya está definida",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.parameter_invalid": "Registro Invalido",
```suggestion
    "tis3d.compiler.parameter_invalid": "Registro inválido",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.parameter_overflow": "Muchos Operandos",
```suggestion
    "tis3d.compiler.parameter_overflow": "Demasiados operandos",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.parameter_underflow": "Faltan Operandos",
```suggestion
    "tis3d.compiler.parameter_underflow": "Faltan operandos",
```
or
```suggestion
    "tis3d.compiler.parameter_underflow": "Operando faltante",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.too_many_columns": "Linea muy larga",
```suggestion
    "tis3d.compiler.too_many_columns": "Línea demasiado larga",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.too_many_lines": "Demasiadas lineas",
```suggestion
    "tis3d.compiler.too_many_lines": "Demasiadas líneas",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.controller.status.incomplete": "El Escaneo ha fallado en completarse",
```suggestion
    "tis3d.controller.status.incomplete": "No se pudo completar el escaneo",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.controller.status.multiple_controllers": "Multiples Controladores",
```suggestion
    "tis3d.controller.status.multiple_controllers": "Varios controladores",
```
or
```suggestion
    "tis3d.controller.status.multiple_controllers": "Múltiples controladores",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.controller.status.too_complex": "Muy Complejo",
```suggestion
    "tis3d.controller.status.too_complex": "Demasiado complejo",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.manual.items": "Items",
```suggestion
    "tis3d.manual.items": "Ítems",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.manual.warning.missing.image": "Imagen no Encontrada.",
```suggestion
    "tis3d.manual.warning.missing.image": "Imagen no encontrada.",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.manual.warning.missing.item": "Item no Disponible.",
```suggestion
    "tis3d.manual.warning.missing.item": "Ítem no disponible.",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.book_code.error_on_next_page": "Error en la siguiente pagina:",
```suggestion
    "tis3d.book_code.error_on_next_page": "Error en la página siguiente:",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.book_code.error_on_previous_page": "Error en la anterior pagina:",
```suggestion
    "tis3d.book_code.error_on_previous_page": "Error en la página anterior:",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.compiler.label_not_found": "Etiqueta no encontrada",
```suggestion
    "tis3d.compiler.label_not_found": "Etiqueta indefinida",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.tooltip.book_code": "§7Usa un libro en un modulo de ejecucion instalado para conseguir una copia.",
```suggestion
    "tis3d.tooltip.book_code": "§7Usa un libro sobre un módulo de ejecución instalado para obtener una copia.",

```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.tooltip.book_manual": "§7Usa un libro en un bloque controlador para conseguir una copia.",
```suggestion
    "tis3d.tooltip.book_manual": "§7Usa un libro sobre un bloque de controlador para obtener una copia.",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "tis3d.tooltip.key": "§7Agachate mientras estas sujetando para recibir puertos en una cara de la cubierta."
```suggestion
    "tis3d.tooltip.key": "§7Agachate mientras estas sujetando para recibir puertos en una cara de la carcasa."
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "block.tis3d.casing": "Cubierta",
```suggestion
    "block.tis3d.casing": "Carcasa",
```

2020-10-25 13:44 UTC, FlashyReese commented on src/main/resources/assets/tis3d/lang/es_es.json
> +    "item.tis3d.module_random": "Módulo Random",
Depending on context here
```suggestion
    "item.tis3d.module_random": "Módulo Randomizador",
```

2021-08-05 12:31 UTC, closed without merging