1.7.10 Backports
MightyPirates/TIS-3D pull request #64
Opened 2017-06-23 00:16 UTC by mpevner

A friend was stuck with 1.7.10 for assorted reasons so I backported features. Then it snowballed including fixes/updates/&c. There will most likely also be an attempt to backport the Terminal module, but I am not much of a modmaker.

2017-06-29 23:53 UTC, fnuecke commented
Github y u no notify me D:

Thanks a lot! Will review and test tomorrow!

2017-06-30 03:14 UTC, mpevner commented
Awesome! I'll try and hack at the Terminal module over the weekend, though it's going to be a bit kludgy most likely.

2017-06-30 20:21 UTC, fnuecke requested changes
Looks good, just a few questions mostly on commented out code lines -- don't want to just remove them / re-enable them without knowing if those were forgotten or deliberately disabled :)

Only piece I noticed missing was the disabled tag syncing for the ROM (those bytes are not used on the client, so syncing the tag over is unnecessary traffic). Mind back-porting that too?

Thanks again!

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/client/gui/GuiModuleTerminal.java
> +        //GlStateManager.disableTexture2D();
Did you deliberately not port those to their corresponding GL calls (because it caused bugs in 1.7.10 or something)?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/init/Items.java
> +        ((ItemModule) modules.get(Constants.NAME_ITEM_MODULE_READ_ONLY_MEMORY)).
Looks like the `setShareTag` in `ItemModule` is missing, mind backporting that, too?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/item/ItemBookCode.java
> +//import net.minecraftforge.common.util.Constants;
Left in as a reminder or can this be removed?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/item/ItemModule.java
> +    //final ItemStack stack,
Can be removed, no?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/item/ItemModule.java
> +//import net.minecraft.util.math.BlockPos;
Left as a reminder or can this be removed?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleExecution.java
> +        //RenderUtil.drawQuad();
Can be removed, no?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleRandomAccessMemory.java
> +        //final ItemStack heldItem,
Can be removed?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleStack.java
> +        //RenderUtil.drawQuad();
Can be removed?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +        //GlStateManager.enableBlend();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +        //GlStateManager.disableBlend();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +        //GlStateManager.disableTexture2D();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +        //GlStateManager.enableTexture2D();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +            //GlStateManager.disableTexture2D();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +            //GlStateManager.enableTexture2D();
Deliberately not ported to GL call?

2017-06-30 20:21 UTC, fnuecke commented on src/main/java/li/cil/tis3d/common/module/ModuleTerminal.java
> +            //world.playSound(null, getCasing().getPosition(), SoundEvents.BLOCK_NOTE_PLING, SoundCategory.BLOCKS, 0.3f, 2f);
Forgotten or should I look into how to backport this call?

2017-06-30 22:45 UTC, mpevner commented
If I did my math right GlStateManager.disableTexture2D(); == GL11.glDisable(GL11.GL_TEXTURE_2D); and ditto for Enable. I've got the stragglers you've caught cleaned up; good catches! Commented out lines were to make sure I actually translated the call (and not forget it. Case in point, if you dont bind a texture, things render.... Interestingly.)

As for sound, that got overlooked. I'll have an edit shortish.

2017-07-08 17:56 UTC, fnuecke approved these changes

2017-07-09 14:53 UTC, merged

2017-07-09 14:55 UTC, fnuecke commented
Sorry for the delay, had a pretty busy week. Looks good! I went ahead and backported what remained (looking at a diff with the 1.12 branch), such as side locking and a few small fixes. Thanks again for doing the bulk of the update!